// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddOrUpdateRepairOrderReducer from "../add_or_update_repair_order_reducer";
import AddTransferOrdersReducer from "../add_transfer_orders_reducer";
import DeleteRepairOrderReducer from "../delete_repair_order_reducer";
import RemoveTransferOrderReducer from "../remove_transfer_order_reducer";
import SetAllPartsAreHereStatusReducer from "../set_all_parts_are_here_status_reducer";
import UpdateNotesReducer from "../update_notes_reducer";
import UpdateTechReducer from "../update_tech_reducer";

export type AddOrUpdateRepairOrderParams = __Infer<typeof AddOrUpdateRepairOrderReducer>;
export type AddTransferOrdersParams = __Infer<typeof AddTransferOrdersReducer>;
export type DeleteRepairOrderParams = __Infer<typeof DeleteRepairOrderReducer>;
export type RemoveTransferOrderParams = __Infer<typeof RemoveTransferOrderReducer>;
export type SetAllPartsAreHereStatusParams = __Infer<typeof SetAllPartsAreHereStatusReducer>;
export type UpdateNotesParams = __Infer<typeof UpdateNotesReducer>;
export type UpdateTechParams = __Infer<typeof UpdateTechReducer>;

